### ISSUE TITLE
connection string problem on start up

### ISSUE THREAD

**Issue by amir6mehrabi** [NonFactors/AspNetCore.Template#33]
I have changed ConString in configuration.json  but it shows me this error:

> SqlException: Cannot open database "MvcTemplate" requested by the login. The login failed. Login failed for user 'DESKTOP-FL4FSA2\A'.

**Comment by Muchiachio** [comment]
Seems like a bad connection string, does it work with other tools? Maybe you need to specify username and pass instead of automatic authentication?
