### ISSUE TITLE
Filter language is not changind in localized mvc-grid

### ISSUE THREAD

**Issue by drmatambo** [NonFactors/AspNetCore.Template#36]
I have made localization of the application to about 10 languages, the amount is not relevant, but I have noticed that the mvc-grid filter does not change the language, the English language always appears, it is as if it was cached, or hardcoded.
![image](https://user-images.githubusercontent.com/22444552/95003172-d0dcb000-05dc-11eb-8154-2a5bdd6090e5.png)
In this example, I've selected Spanish but the filter remains in English.

**Comment by drmatambo** [comment]
![image](https://user-images.githubusercontent.com/22444552/95003622-6b3ef280-05e1-11eb-8602-a47ea9db8f01.png)

![image](https://user-images.githubusercontent.com/22444552/95003646-78f47800-05e1-11eb-9db8-0fa5ccc3f092.png)

**Comment by Muchiachio** [comment]
Are localized js files included in the layout?

**Comment by drmatambo** [comment]
Yes sir, all the js files are translated and included in the layout, in the same place where the English language file is unless there are other steps that need to be done that I don't know about.
Thank you very much for answering.

**Comment by drmatambo** [comment]
![image](https://user-images.githubusercontent.com/22444552/95028667-24650180-06a2-11eb-9dc5-1f3f40a5dfa8.png)

**Comment by Muchiachio** [comment]
I mean are they included in the final html as script tags?

**Comment by drmatambo** [comment]
Yes I've included the translated scriptis like this.
 <environment names="Development">
        <script src="~/js/mvc-grid/cultures/mvc-grid.da.js"></script>
        <script src="~/js/mvc-grid/cultures/mvc-grid.de.js"></script>
        <script src="~/js/mvc-grid/cultures/mvc-grid.en.js"></script>
        <script src="~/js/mvc-grid/cultures/mvc-grid.es.js"></script>
        <script src="~/js/mvc-grid/cultures/mvc-grid.fr.js"></script>
        <script src="~/js/mvc-grid/cultures/mvc-grid.it.js"></script>
        <script src="~/js/mvc-grid/cultures/mvc-grid.lt.js"></script>
        <script src="~/js/mvc-grid/cultures/mvc-grid.nl.js"></script>
        <script src="~/js/mvc-grid/cultures/mvc-grid.pb.js"></script>
        <script src="~/js/mvc-grid/cultures/mvc-grid.pt.js"></script>
        <script src="~/js/mvc-grid/cultures/mvc-grid.ru.js"></script>
    </environment>
If it is not the way can you please line up the correct way step by step of localizing the mvc-grid. All other localized js files seems that are working 
Thank you

**Comment by Muchiachio** [comment]
Might need to change `MvcGrid.prototype.lang` to `MvcGrid.lang` depending on which grid version you are.
You can always check on [grid localization](https://mvc6-grid.azurewebsites.net/localization) page.

**Comment by drmatambo** [comment]
A cordial greeting.
I have made all the proposed changes, cleaned the solution, and rebuilt it, but the language change in the mvc-grib filters still does not work. I am using the latest version 6.2 of the mvc-grid. Thanks for helping to find a solution.

**Comment by Muchiachio** [comment]
Don't know what else could be wrong, just some local problem. You should be able to easily debug the issue by putting breakpoints on `MvcGrid.lang` setters in the code base and checking [what is being used in the grid](https://github.com/NonFactors/AspNetCore.Template/blob/3cff4f503665a822edac3e8e3aca529cab780b72/src/MvcTemplate.Web/wwwroot/js/mvc-grid/mvc-grid.js#L894).

**Comment by drmatambo** [comment]
After following all the instructions, about debugging, for some reason that I can't explain because I don't have so much experience, I have noticed that the JSON localized files are being loaded an working correctly according to the selected language. However, all the localizations in js format are not loaded, the English language is always loaded. It seems as if there is a query selector that always returns the same language, and I cannot locate where the language is selected. I made some screenshots.

**Comment by drmatambo** [comment]
![image](https://user-images.githubusercontent.com/22444552/95614812-68238680-0a67-11eb-9ff7-6b4ed45c4c29.png)

Before entering the access credentials and with the Spanish selected in the Dropdown. All files in js format appear.

**Comment by drmatambo** [comment]
After entering the credentials and with the Spanish language selected, you arrive at the main page and only the js files of the English language appear selected even with Spanish selected as the interface language

![image](https://user-images.githubusercontent.com/22444552/95615284-437bde80-0a68-11eb-9b3f-0f8bb8655642.png)

**Comment by Muchiachio** [comment]
There are two layouts public and private, you probably only included the files to public layout.

**Comment by drmatambo** [comment]
Oh yes I have only in public layout, let me try to put also in private layout

**Comment by drmatambo** [comment]
The problem has been solved, it was indeed because the references of the js files as script tags had not been included in both layouts. Now it works wonderfully. Many thanks.
