### ISSUE TITLE
Cliking the Home Button or the link to Home, resets the selected language to configured as Default

### ISSUE THREAD

**Issue by drmatambo** [NonFactors/AspNetCore.Template#37]
By clicking the home button, the selected language is being reset to the configured as the default language of the application, I have tried it by changing the default language to Spanish, the same thing happens, the selected language will be reset to Spanish.
I appreciate any solution to the problem.

![image](https://user-images.githubusercontent.com/22444552/95003412-742ec480-05df-11eb-8ab9-2f5039fed59d.png)

Thank you

**Comment by Muchiachio** [comment]
You can append the current query [here](https://github.com/NonFactors/AspNetCore.Template/blob/1992a49118dc2c22c18063cbd005196448d1b8f6/src/MvcTemplate.Web/Views/Shared/_PrivateLayout.cshtml#L61). We used to do that, but we quickly ran into the problems of different format numbers/dates/texts transferring to the next culture incorrectly, so we removed it from the template.
