### ISSUE TITLE
AutoMapper version

### ISSUE THREAD

**Issue by msavara** [NonFactors/AspNetCore.Template#40]
I wants to tell you, you did a very good job :) but i have an question about AutoMapper. Everything in nuget packages is on the latest version except Automapper. That version is from 6/3/2019. Can you tell me if this had reason and why it's not on latest 10.1.1 :) thank you very much for answer.

**Comment by Muchiachio** [comment]
Mainly three reasons
- there is no static `Mapper` class, which isn't that big of a problem as mapping is done in data layer classes.
- no way to enable automatic mapping, resulting in hundreds of empty `Mapper.Map<Account, AccountCreateView>()` configs.
- it requires all properties being mapped or ignored, which again needs a lot of configuration to be.

We loved the automatic aspect of "auto" mapper, but with latest releases it's heading to become more and more explicit configuration first , which quickly explodes to thousands of lines. All of these reasons have some kind of workarounds, but we are waiting until there is a very needed new feature or there is a configurable endpoint for these issues.

**Comment by msavara** [comment]
Now i understand, i didn't know that about AutoMapper before. Thank you for exhaustive answer.

**Comment by aynur-safin** [comment]
If I may, I want to continue this question))
How do you feel about such an implementation?

I spied it in the BlazorShop project (https://github.com/kalintsenkov/BlazorShop) and altered it a bit to be able to use new versions of AutoMapper with "AspNetCore.Template".

Default implementations in interfaces:

```
    using AutoMapper;

    public interface IMapFrom<TModel>
        where TModel : class
    {
        void Mapping(Profile mapper)
        {
            mapper.CreateMap(typeof(TModel), this.GetType());
            mapper.CreateMap(this.GetType(), typeof(TModel));
        }
    }
```

AutoMapper profile for custom mapping:

```
    public class MappingProfile : Profile
    {
        public MappingProfile()
            => this.ApplyMappingsFromAssembly(typeof(ApplicationSettings).Assembly);

        private void ApplyMappingsFromAssembly(Assembly assembly)
        {
            var types = assembly
                .GetExportedTypes()
                .Where(t => t
                    .GetInterfaces()
                    .Any(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IMapFrom<>)))
                .ToList();

            foreach (var type in types)
            {
                var instance = Activator.CreateInstance(type);

                const string mappingMethodName = "Mapping";

                var methodInfo = type.GetMethod(mappingMethodName)
                                 ?? type.GetInterface("IMapFrom`1")?.GetMethod(mappingMethodName);

                methodInfo?.Invoke(instance, new object[] { this });
            }
        }
    }
```

Startup.cs:
```
...
services.AddAutoMapper(Assembly.GetExecutingAssembly());
```

Usage example:
```
public class AccountView : AView, IMapFrom<Account>
{...}
```

Custom mapping:
```
    public class RoleView : AView, IMapFrom<Role>
    {
        [Required]
        [LookupColumn]
        [StringLength(128)]
        public String? Title { get; set; }

        public MvcTree Permissions { get; set; }

        public RoleView()
        {
            Permissions = new MvcTree();
        }

        public void Mapping(Profile mapper)
        {
            mapper.CreateMap<Role, RoleView>()
                .ForMember(role => role.Permissions, member => member.Ignore());

            mapper.CreateMap<RoleView, Role>()
                .ForMember(role => role.Permissions, member => member.MapFrom(_ => new List<RolePermission>()));
        }
    }
```

**Comment by Muchiachio** [comment]
Interesting idea to have on the view.
Helps reducing the mapping of everything to everything in the project and keeping the mappings near the classes.

I guess I can try going over auto mapper changes again and do this on a live project to see how much of a pain it is to migrate :)
