### ISSUE TITLE
configuration.json encoding problem

### ISSUE THREAD

**Issue by marcelo-maciel** [NonFactors/AspNetCore.Template#41]
When I added a new language, "Português" on configuration.json, the error below occurs.
To solve character problems, configuration.json need be a UTF-8 file.

{
  "Name": "Português",
  "Culture": "pt-BR",
  "Abbreviation": "pt"
},

![image](https://user-images.githubusercontent.com/4993482/104118565-e0b90e00-5308-11eb-8282-c722d2acd601.png)

After change configuration.json to UTF-8

![image](https://user-images.githubusercontent.com/4993482/104118740-e5ca8d00-5309-11eb-80b4-3ebc0a1e92f2.png)

**Comment by Muchiachio** [comment]
Weird, it does say `UTF-8` for me and I don't know if there is a way to change how aspnet framework reads the files.
![image](https://user-images.githubusercontent.com/6647444/104122223-65794b80-534c-11eb-88d1-ecf55802abca.png)

**Comment by marcelo-maciel** [comment]
I found a interesting thing.
I downloaded  2 zips of current code. At first, i oppened with Visual Studio 2019 and the problem occurs. To solve, i use "save file as" and select the utf-8 file without BOM. With BOM works too.
On second download, i opened with vscode and all worked without any problem....
Are you using vscode?

**Comment by marcelo-maciel** [comment]
Oppening the same project now with VS2019, it runs well.
I unziped the project again, selected configuration.json and when opened "Advnced Save Options" I can see bellow settings. 
![image](https://user-images.githubusercontent.com/4993482/104139080-b0fd1b00-5387-11eb-8f00-33891bfe7efa.png)

**Comment by Muchiachio** [comment]
Yes, I usually use VS code, but it also works with VS. I get this
![image](https://user-images.githubusercontent.com/6647444/104194124-954a5100-5429-11eb-9f6b-2883f3760ccc.png)

 Maybe you have `Tools > Options > Environment > Documents > Save documents as Unicode when data cannot be saved in codepage` disabled, so it saves using some random codepage and then aspnet framework reads it as UTF8 and mangles the letters.

**Comment by marcelo-maciel** [comment]
No problem, thanks!
