### ISSUE TITLE
Multiple roles

### ISSUE THREAD

**Issue by marcelo-maciel** [NonFactors/AspNetCore.Template#46]
What do you think about an account have multiple roles?

**Comment by Muchiachio** [comment]
Current role tree allows any permission union to be configured without using multiple roles.
We also never got that kind of feedback form actual users/system administrators, so there are no plans to do now.

**Comment by marcelo-maciel** [comment]
The question is not capacities of configuration, but quantity.
Enabling a user have more than one role, the total number of roles are much lower and easy to maintain.
